2023-12-08 17:19:11,470 INFO    StreamThr :42098 [internal.py:wandb_internal():86] W&B internal server running at pid: 42098, started at: 2023-12-08 17:19:11.470363
2023-12-08 17:19:11,471 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status
2023-12-08 17:19:11,480 INFO    WriterThread:42098 [datastore.py:open_for_write():85] open: /Users/silviaromanato/Desktop/EPFL/MA3/DeepLearning/biomed-team4/multimodal/wandb/run-20231208_171911-g1yq05zt/run-g1yq05zt.wandb
2023-12-08 17:19:11,481 DEBUG   SenderThread:42098 [sender.py:send():382] send: header
2023-12-08 17:19:11,558 DEBUG   SenderThread:42098 [sender.py:send():382] send: run
2023-12-08 17:19:11,905 ERROR   SenderThread:42098 [internal_api.py:execute():373] 404 response executing GraphQL.
2023-12-08 17:19:11,906 ERROR   SenderThread:42098 [internal_api.py:execute():374] {"errors":[{"message":"project not found","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-12-08 17:19:11,906 ERROR   SenderThread:42098 [sender.py:send_run():987] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/Users/silviaromanato/.conda/envs/lastenv/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/silviaromanato/.conda/envs/lastenv/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/silviaromanato/.conda/envs/lastenv/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/silviaromanato/.conda/envs/lastenv/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/silviaromanato/.conda/envs/lastenv/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/Users/silviaromanato/.conda/envs/lastenv/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/silviaromanato/.conda/envs/lastenv/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 985, in send_run
    self._init_run(run, config_value_dict)
  File "/Users/silviaromanato/.conda/envs/lastenv/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 1027, in _init_run
    server_run, inserted, server_messages = self._api.upsert_run(
  File "/Users/silviaromanato/.conda/envs/lastenv/lib/python3.8/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/Users/silviaromanato/.conda/envs/lastenv/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/Users/silviaromanato/.conda/envs/lastenv/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 2212, in upsert_run
    response = self.gql(
  File "/Users/silviaromanato/.conda/envs/lastenv/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/Users/silviaromanato/.conda/envs/lastenv/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/Users/silviaromanato/.conda/envs/lastenv/lib/python3.8/site-packages/wandb/util.py", line 965, in check_retry_fn
    return fallback_retry_fn(e)
  File "/Users/silviaromanato/.conda/envs/lastenv/lib/python3.8/site-packages/wandb/util.py", line 907, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-12-08 17:19:15,040 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:19:16,586 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: keepalive
2023-12-08 17:19:16,928 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:19:20,055 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:19:21,603 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: keepalive
2023-12-08 17:19:21,943 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:19:25,073 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:19:26,628 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: keepalive
2023-12-08 17:19:26,968 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:19:30,098 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:19:31,652 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: keepalive
2023-12-08 17:19:31,992 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:19:34,721 INFO    StreamThr :42098 [internal.py:wandb_internal():86] W&B internal server running at pid: 42098, started at: 2023-12-08 17:19:34.721461
2023-12-08 17:19:34,722 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status
2023-12-08 17:19:34,731 INFO    WriterThread:42098 [datastore.py:open_for_write():85] open: /Users/silviaromanato/Desktop/EPFL/MA3/DeepLearning/biomed-team4/multimodal/wandb/run-20231208_171934-3dwl3op1/run-3dwl3op1.wandb
2023-12-08 17:19:34,732 DEBUG   SenderThread:42098 [sender.py:send():382] send: header
2023-12-08 17:19:34,809 DEBUG   SenderThread:42098 [sender.py:send():382] send: run
2023-12-08 17:19:35,119 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:19:35,196 INFO    SenderThread:42098 [dir_watcher.py:__init__():211] watching files in: /Users/silviaromanato/Desktop/EPFL/MA3/DeepLearning/biomed-team4/multimodal/wandb/run-20231208_171934-3dwl3op1/files
2023-12-08 17:19:35,197 INFO    SenderThread:42098 [sender.py:_start_run_threads():1136] run started: 3dwl3op1 with start time 1702052374.720573
2023-12-08 17:19:37,015 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:19:39,838 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: keepalive
2023-12-08 17:19:40,145 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:19:40,214 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:19:42,038 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:19:44,859 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: keepalive
2023-12-08 17:19:45,167 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:19:45,236 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:19:47,052 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:19:49,887 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: keepalive
2023-12-08 17:19:50,188 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:19:50,257 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:19:52,076 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:19:54,917 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: keepalive
2023-12-08 17:19:55,212 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:19:55,275 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:19:57,101 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:19:59,941 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: keepalive
2023-12-08 17:20:00,230 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:00,300 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:02,126 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:04,971 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: keepalive
2023-12-08 17:20:05,253 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:05,321 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:07,143 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:09,991 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: keepalive
2023-12-08 17:20:10,276 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:10,345 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:12,165 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:15,018 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: keepalive
2023-12-08 17:20:15,301 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:15,368 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:17,184 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:20,043 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: keepalive
2023-12-08 17:20:20,321 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:20,386 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:22,205 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:25,072 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: keepalive
2023-12-08 17:20:25,334 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:25,407 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:27,226 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:30,096 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: keepalive
2023-12-08 17:20:30,351 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:30,428 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:32,249 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:35,116 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: keepalive
2023-12-08 17:20:35,371 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:35,451 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:37,267 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:40,137 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: keepalive
2023-12-08 17:20:40,394 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:40,477 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:42,293 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:45,168 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: keepalive
2023-12-08 17:20:45,419 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:45,498 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:47,312 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:50,194 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: keepalive
2023-12-08 17:20:50,441 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:50,516 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:52,339 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:55,222 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: keepalive
2023-12-08 17:20:55,463 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:55,540 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:20:57,356 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:21:00,252 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: keepalive
2023-12-08 17:21:00,483 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:21:00,558 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:21:02,378 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:21:05,284 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: cancel
2023-12-08 17:21:05,285 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: cancel
2023-12-08 17:21:05,508 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:21:05,577 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:21:07,401 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:21:10,529 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:21:10,589 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:21:12,422 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:21:15,551 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:21:15,607 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:21:17,447 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:21:20,568 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:21:20,627 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
2023-12-08 17:21:22,460 DEBUG   HandlerThread:42098 [handler.py:handle_request():146] handle_request: status_report
